import { readFileSync, writeFileSync } from 'fs';

export function writePackageVersion() {
  const packageJson = JSON.parse(readFileSync('package.json', 'utf8'));
  const version = packageJson?.version;

  const content = `// DO NOT EDIT: file is generated by build process
export const PACKAGE_VERSION = '${version}';
`;
  writeFileSync('./src/version.ts', content, 'utf-8');
}

writePackageVersion();
