name: CI

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Linter
        run: npm run check

      - name: Build
        run: npm run build

      - name: Unit Tests
        run: npm run test

      - name: Integration Test
        env:
          TEST_API_KEY: ${{ secrets.TEST_API_KEY }}
          TEST_API_URL: ${{ vars.TEST_API_URL || 'https://api.workflowai.dev' }}
          TEST_TASK_ID: ${{ vars.TEST_TASK_ID || 'get-celebrity-last-name' }}
          TEST_TASK_SCHEMA_ID: ${{ vars.TEST_TASK_SCHEMA_ID || '1' }}
        run: npx tsx ./bin/integration-testing/run.ts

      - name: Publish to NPM
        if: github.ref == 'refs/heads/main'
        run: npx tsx ./bin/npm-publish
