name: API code-generation

on:
  workflow_dispatch:
    inputs:
      branch:
        type: choice
        description: 'Branch/environment to generate API code for'
        required: true
        options:
          - main
          - dev

jobs:
  codegen:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # We always base ourselves on main branch, aka prod
          ref: refs/heads/main
      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          check-latest: true
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run codegen
        run: npm run codegen
        env:
          # Use either prod or staging api to generate code
          WORKFLOWAI_API_URL: ${{ (github.event.inputs.branch == 'main' && 'https://api.workflowai.com') || 'https://api.workflowai.dev' }}

      - name: Check if any file changed
        id: has-git-diff
        continue-on-error: true
        run: npx tsx ./bin/codegen/has-git-diff.ts

      - name: Bump package version
        if: steps.has-git-diff.outcome == 'success'
        run: npm version ${{ (github.event.inputs.branch == 'main' && 'patch') || 'prepatch' }} -w=@workflowai/api

      - name: Commit and push changes
        if: steps.has-git-diff.outcome == 'success'
        id: commit-push
        uses: devops-infra/action-commit-push@master
        # https://github.com/devops-infra/action-commit-push
        with:
          github_token: ${{ github.token }}
          add_timestamp: false
          commit_message: Auto generation of OpenAPI types
          force: false
          target_branch: auto-codegen/${{ github.run_id }}

      - name: Create pull request
        if: steps.has-git-diff.outcome == 'success'
        uses: devops-infra/action-pull-request@v0.5.5
        # https://github.com/marketplace/actions/github-action-for-creating-pull-requests
        with:
          github_token: ${{ github.token }}
          source_branch: ${{ steps.commit-push.outputs.branch_name }}
          target_branch: ${{ github.event.inputs.branch }}
          title: Auto API code-generation (${{ github.event.inputs.branch }})
          reviewer: guillaq
          assignee: pierreliefauche
          draft: false

      - name: Run CI workflow
        if: steps.has-git-diff.outcome == 'success'
        uses: benc-uk/workflow-dispatch@v1
        # https://github.com/marketplace/actions/workflow-dispatch
        with:
          workflow: ci.yml
          ref: refs/heads/${{ steps.commit-push.outputs.branch_name }}
