# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Quality

on: [push]

jobs:
  quality:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Linter
        run: npm run check

      - name: Build
        run: npm run build

      - name: Unit Tests
        run: npm run test

      - name: Integration Test
        env:
          TEST_API_KEY: ${{ secrets.TEST_API_KEY }}
          TEST_API_URL: ${{ secrets.TEST_API_URL || 'https://dev.workflowai.dev' }}
          TEST_TASK_ID: ${{ secrets.TEST_TASK_ID || 'get-celebrity-last-name' }}
          TEST_TASK_SCHEMA_ID: ${{ secrets.TEST_TASK_SCHEMA_ID || '1' }}
        run: npx tsx ./bin/integration-testing/run.ts
