name: tags

on:
  push:
    tags:
      - '*@*'

permissions:
  contents: read
  id-token: write

env:
  TAG_NAME: ${{ github.ref_name }}

jobs:
  quality:
    uses: ./.github/workflows/.quality.yml
    secrets: inherit

  splits:
    runs-on: ubuntu-latest

    steps:
      - name: Set package and version
        id: set_package_and_version
        run: |
          echo "package=${TAG_NAME%%@*}" >> $GITHUB_OUTPUT
          echo "version=${TAG_NAME#*@}" >> $GITHUB_OUTPUT
    outputs:
      package: ${{ steps.set_package_and_version.outputs.package }}
      version: ${{ steps.set_package_and_version.outputs.version }}

  publish:
    needs: splits
    uses: ./.github/workflows/.publish.yml
    secrets: inherit
    with:
      tag: latest
      expectedVersion: ${{ needs.splits.outputs.version }}
      package: ${{ needs.splits.outputs.package }}
